version: '3'
services:
  zoo1:
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    volumes:
      - ./data/:/home/jovyan/data
      - ./notebooks/:/home/jovyan/work
    ports:
      - 8888:8888
